---

- name: apply standard RHEL configuration
  hosts:
    - all
  vars:
    # selinx vars
    selinux_policy: targeted
    selinux_state: permissive

    # timesync vars
    timesync_ntp_servers:
      - hostname: 0.rhel.pool.ntp.org
        iburst: yes
      - hostname: 1.rhel.pool.ntp.org
        iburst: yes
      - hostname: 2.rhel.pool.ntp.org
        iburst: yes
      - hostname: 3.rhel.pool.ntp.org
        iburst: yes

    # metrics vars
    metrics_retention_days: 7

    # tlog vars
    tlog_scope_sssd: some
    tlog_users_sssd:
      - root

  pre_tasks:
    - name: set /etc/resolv.conf
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          search lab.msp.redhat.com redhat.com
          nameserver 10.15.108.148
          nameserver 10.15.108.109
          options rotate timeout:1 retries:1

    - name: install satellite certificate bundle
      ansible.builtin.yum:
        name: http://satellite05.lab.msp.redhat.com/pub/katello-ca-consumer-latest.noarch.rpm
        disable_gpg_check: yes
        state: present

    - name: register to satellite
      community.general.redhat_subscription:
        activationkey: ak-rhel8-production
        org_id: MSP_Lab

    - name: enable repositories
      community.general.rhsm_repository:
        name:
          - rhel-8-for-x86_64-baseos-rpms
          - rhel-8-for-x86_64-appstream-rpms
          - satellite-tools-6.9-for-rhel-8-x86_64-rpms
        purge: yes

  roles:
    - redhat.insights.insights_client
    - redhat.rhel_system_roles.selinux
    - redhat.rhel_system_roles.timesync
    - redhat.rhel_system_roles.metrics
    - redhat.rhel_system_roles.tlog
