---

- name: apply standard RHEL configuration
  hosts:
    - all
  vars:
    # selinx vars
    selinux_policy: targeted
    selinux_state: enforcing

    # timesync vars
    timesync_ntp_servers:
      - hostname: 0.rhel.pool.ntp.org
        iburst: yes
      - hostname: 1.rhel.pool.ntp.org
        iburst: yes
      - hostname: 2.rhel.pool.ntp.org
        iburst: yes
      - hostname: 3.rhel.pool.ntp.org
        iburst: yes

    # metrics vars
    metrics_retention_days: 7

    # tlog vars
    tlog_scope_sssd: some
    tlog_users_sssd:
      - root
  roles:
#   - register to satellite
    - redhat.rhel_system_roles.selinux
    - redhat.rhel_system_roles.timesync
    - redhat.rhel_system_roles.metrics
    - redhat.rhel_system_roles.tlog
